# Generated by Django 3.1.7 on 2021-04-05 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('emailid', models.EmailField(max_length=254)),
                ('domain', models.CharField(max_length=20)),
                ('bank_acc_number', models.IntegerField()),
                ('IFSC', models.CharField(max_length=12)),
                ('Pan', models.CharField(max_length=10)),
                ('Bank_name', models.CharField(max_length=20)),
                ('Location', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('collegeid', models.CharField(max_length=20)),
                ('collegename', models.CharField(max_length=20)),
                ('emailid', models.EmailField(max_length=254)),
                ('domain', models.CharField(max_length=20)),
                ('duration', models.IntegerField()),
                ('datestart', models.DateField()),
                ('dateend', models.DateField()),
                ('food', models.CharField(max_length=10)),
                ('training', models.CharField(max_length=20)),
            ],
        ),
    ]
