# Generated by Django 3.1.7 on 2021-04-05 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quintet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='dateend',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='users',
            name='datestart',
            field=models.CharField(max_length=20),
        ),
    ]
