# Generated by Django 3.1.7 on 2021-04-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quintet', '0005_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainers',
            name='bank_acc_number',
            field=models.IntegerField(max_length=200),
        ),
        migrations.AlterModelTable(
            name='admin',
            table='admin',
        ),
        migrations.AlterModelTable(
            name='trainers',
            table='trainers',
        ),
        migrations.AlterModelTable(
            name='users',
            table='users',
        ),
    ]
