# Generated by Django 3.1.7 on 2021-04-07 10:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quintet', '0006_auto_20210407_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainers',
            name='IFSC',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='trainers',
            name='Pan',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='trainers',
            name='bank_acc_number',
            field=models.BigIntegerField(),
        ),
    ]
