# Generated by Django 3.1.7 on 2021-04-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quintet', '0008_remove_users_collegeid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('emailid', models.EmailField(max_length=254)),
                ('collegename', models.CharField(max_length=200)),
                ('datestart', models.DateField()),
                ('dateend', models.DateField()),
                ('duration', models.IntegerField()),
                ('training', models.CharField(max_length=20)),
                ('domain', models.CharField(max_length=20)),
                ('food', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'users1',
            },
        ),
    ]
