# Generated by Django 3.1.7 on 2021-04-16 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quintet', '0009_users1'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainers',
            name='fees',
            field=models.IntegerField(default=500),
            preserve_default=False,
        ),
    ]
