# Generated by Django 3.1.7 on 2021-04-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quintet', '0011_auto_20210416_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='users1',
            name='travel',
            field=models.IntegerField(default=500),
            preserve_default=False,
        ),
    ]
