# Generated by Django 3.1.7 on 2021-04-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quintet', '0012_users1_travel'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='collegeid',
            field=models.CharField(default='SJBIT', max_length=20),
            preserve_default=False,
        ),
    ]
